#!/bin/bash
# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

python -m correlators ../systems/A100.24_L24_T48_beta190_mul0100_musig150_mudel190_kappa1632550/ev120/TB2_SO_LI6_new/
